package guis;

import entidades.Usuario;
import interfaces.INegocioFachada;
import java.util.Arrays;
import net.miginfocom.swing.MigLayout;

public class Home extends javax.swing.JLayeredPane {
    private ChatPanel chatPanel;
    private Usuario principal;
    private INegocioFachada negFac;
    private Configuracion config;
    private Menu_Right menuRight;
    
    public Home(Usuario principal, INegocioFachada negFac) {
        initComponents();
        this.principal = principal;
        this.negFac = negFac;
        init();
    }
    
    private void init() {
        this.layoutDefault();
        this.add(new Menu_Left(this, principal, negFac));
    }
    
    public void layoutDefault(){
        setLayout(new MigLayout("fillx, filly", "0[fill, 200!]5[fill, 100%]", "0[fill]0"));
    }
    
    public void layoutConfig(){
        setLayout(new MigLayout("fillx, filly", "0[fill, 200!]5[fill, 100%]0[fill, 250!]0", "0[fill]0"));
    }
    
    public void toggleChatPanel(){
        if(chatPanel == null) return;
        if(Arrays.asList(this.getComponents()).contains(chatPanel)){
            this.remove(chatPanel);
        }else {
            this.add(chatPanel);
        }
    }
    
    public void toggleCambiarPassword(){
        if(Arrays.asList(this.getComponents()).contains(this.getMenuRight())){
            this.remove(this.getMenuRight());
            this.layoutDefault();
        }else{
            this.setMenuRight(new Menu_Right(negFac, this));
            this.layoutConfig();
            this.add(this.getMenuRight());
        }
        this.repaint();
        this.revalidate(); 
    }

    public Configuracion getConfig() {
        return config;
    }

    public void setConfig(Configuracion config) {
        this.config = config;
    }
    
    public ChatPanel getChatPanel() {
        return chatPanel;
    }

    public void setChatPanel(ChatPanel chatPanel) {
        this.chatPanel = chatPanel;
    }

    public Usuario getPrincipal() {
        return principal;
    }

    public void setPrincipal(Usuario principal) {
        this.principal = principal;
    }

    public Menu_Right getMenuRight() {
        return menuRight;
    }

    public void setMenuRight(Menu_Right menuRight) {
        this.menuRight = menuRight;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
