package guis;

import interfaces.INegocioFachada;
import javax.swing.JOptionPane;
import swingComponents.LimitJTextField;

public class Menu_Right extends javax.swing.JPanel {

    private INegocioFachada negFac;
    private Home home;

    public Menu_Right(INegocioFachada negFac, Home home) {
        this.negFac = negFac;
        this.home = home;
        initComponents();
        this.txtConfPassword.setDocument(new LimitJTextField(50));
        this.txtNewPassword.setDocument(new LimitJTextField(50));
    }
    
    private boolean validarCampos() {
        StringBuffer mensaje = new StringBuffer();
        String newPass=new String(txtNewPassword.getPassword());
        String confPass=new String(txtConfPassword.getPassword());
        if(newPass.isEmpty()){
            mensaje.append("La nueva contraseña no puede ser vacía.\n");
        }
        if(newPass.length()<4){
            mensaje.append("La contraseña debe tener mínimo 4 caracteres.\n");
        }
        if(!newPass.equals(confPass)){
            mensaje.append("Las contraseñas no coinciden.\n");
        }
        
       if (mensaje.length() == 0) {
           return true;
        }
        JOptionPane.showMessageDialog(home, mensaje, "Información invalida", JOptionPane.INFORMATION_MESSAGE);
        return false;
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNewPassword = new javax.swing.JLabel();
        lblConfPassword = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNewPassword = new javax.swing.JPasswordField();
        txtConfPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(17, 27, 33));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 59, 67)));

        lblNewPassword.setText("Nueva Contraseña");
        lblNewPassword.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblNewPassword.setForeground(new java.awt.Color(255, 255, 255));

        lblConfPassword.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblConfPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblConfPassword.setText("Confirmar Contraseña");

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cambiar Contraseña");
        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));

        btnAceptar.setBackground(new java.awt.Color(32, 44, 51));
        btnAceptar.setForeground(new java.awt.Color(63, 166, 129));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorderPainted(false);
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(32, 44, 51));
        btnCancelar.setForeground(new java.awt.Color(63, 166, 129));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtNewPassword.setBackground(new java.awt.Color(32, 44, 51));
        txtNewPassword.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNewPassword.setForeground(new java.awt.Color(255, 255, 255));

        txtConfPassword.setBackground(new java.awt.Color(32, 44, 51));
        txtConfPassword.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtConfPassword.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtConfPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNewPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblConfPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(validarCampos()){
            String mensaje="No se logró cambiar la contraseña.";
            int opcion = JOptionPane.showConfirmDialog(home, "¿Está seguro de cambiar la contraseña?","Cambiar contraseña",JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if(opcion != JOptionPane.YES_OPTION)
                return;
            try {
                String password =new String(txtConfPassword.getPassword());
                home.getPrincipal().setPassword(password);
                negFac.actualizarPassword(home.getPrincipal());
                JOptionPane.showMessageDialog(home, "La contraseña se cambió correctamente", "Usuario actualizado", JOptionPane.INFORMATION_MESSAGE);
                home.toggleCambiarPassword();
            } catch(Exception e){
                JOptionPane.showMessageDialog(home, mensaje, "Error al encriptar", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        home.toggleCambiarPassword();

    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblConfPassword;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField txtConfPassword;
    private javax.swing.JPasswordField txtNewPassword;
    // End of variables declaration//GEN-END:variables
}
